---
# tasks file for docker

- name: Download Docker installation script
  get_url:
    url: https://get.docker.com
    dest: /tmp/get-docker.sh

- name: Run Docker installation script
  command: sh /tmp/get-docker.sh
  become: true
