---
- name: Install and configure PostgreSQL on Ubuntu 22.04
  hosts: db
  become: yes

  vars:
    postgres_password: "postgres"

  tasks:
    - name: Install PostgreSQL
      apt:
        name: postgresql
        state: present
        update_cache: yes

    - name: Ensure PostgreSQL is running
      service:
        name: postgresql
        state: started
        enabled: yes

    - name: Set password for the postgres user
      become_user: postgres
      postgresql_user:
        name: postgres
        password: "{{ postgres_password }}"
        role_attr_flags: 'SUPERUSER'

    - name: Allow password authentication in pg_hba.conf
      lineinfile:
        path: /etc/postgresql/14/main/pg_hba.conf
        regexp: '^host\s+all\s+all\s+127\.0\.0\.1/32\s+.*$'
        line: 'host    all             all             127.0.0.1/32            md5'
        state: present
        backrefs: yes

    - name: Allow password authentication in pg_hba.conf (IPv6)
      lineinfile:
        path: /etc/postgresql/14/main/pg_hba.conf
        regexp: '^host\s+all\s+all\s+::1/128\s+.*$'
        line: 'host    all             all             ::1/128                 md5'
        state: present
        backrefs: yes

    - name: Ensure PostgreSQL is listening on localhost
      lineinfile:
        path: /etc/postgresql/14/main/postgresql.conf
        regexp: '^#?listen_addresses\s*='
        line: "listen_addresses = 'localhost'"

    - name: Restart PostgreSQL to apply changes
      service:
        name: postgresql
        state: restarted
