- name: Deploy PostgreSQL Database
  hosts: db
  become: true
  vars:
    postgres_user: postgres
    postgres_password: postgres

  tasks:
    - name: Ensure APT cache is up to date
      apt:
        update_cache: yes
        cache_valid_time: 300

    - name: Install PostgreSQL
      apt:
        name: postgresql
        state: present
      become: true
      become_user: root
      when: ansible_os_family == "Debian"

    - name: Ensure PostgreSQL is started and enabled
      service:
        name: postgresql
        state: started
        enabled: yes

    - name: Configure PostgreSQL to use password authentication
      lineinfile:
        path: /etc/postgresql/{{ postgresql_version }}/main/pg_hba.conf
        regexp: '^local\s+all\s+postgres\s+peer'
        line: 'local   all             postgres                                md5'
      notify: Restart PostgreSQL

    - name: Install psycopg2 library for Python
      apt:
        name: python3-psycopg2
        state: present
      become: true

    - name: Set PostgreSQL password for the default user
      postgresql_user:
        name: "{{ postgres_user }}"
        password: "{{ postgres_password }}"
        login_user: postgres

  handlers:
    - name: Restart PostgreSQL
      service:
        name: postgresql
        state: restarted