---
- name: Install and configure PostgreSQL on Ubuntu 22.04
  hosts: db
  become: true

  vars:
    postgres_username: "postgres"
    postgres_password: "postgres"

  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Install PostgreSQL server and client
      apt:
        name:
          - postgresql
          - postgresql-client
        state: present

    - name: Ensure PostgreSQL is running
      service:
        name: postgresql
        state: started
        enabled: yes

    - name: Set password for the postgres user using psql
      become: true
      shell: |
        sudo -u postgres psql -c "ALTER USER {{ postgres_username }} WITH PASSWORD '{{ postgres_password }}';"
      args:
        executable: /bin/bash

    - name: Configure md5 authentication for local IPv4
      lineinfile:
        path: /etc/postgresql/14/main/pg_hba.conf
        regexp: '^host\s+all\s+all\s+127\.0\.0\.1/32\s+.*$'
        line: 'host    all             all             127.0.0.1/32            md5'
        state: present
        backrefs: yes

    - name: Configure md5 authentication for local IPv6
      lineinfile:
        path: /etc/postgresql/14/main/pg_hba.conf
        regexp: '^host\s+all\s+all\s+::1/128\s+.*$'
        line: 'host    all             all             ::1/128                 md5'
        state: present
        backrefs: yes

    - name: Configure md5 authentication for all IPv4 addresses
      lineinfile:
        path: /etc/postgresql/14/main/pg_hba.conf
        regexp: '^host\s+all\s+all\s+0\.0\.0\.0/0\s+.*$'
        line: 'host    all             all             0.0.0.0/0               md5'
        state: present
        backrefs: yes

    - name: Configure md5 authentication for all IPv6 addresses
      lineinfile:
        path: /etc/postgresql/14/main/pg_hba.conf
        regexp: '^host\s+all\s+all\s+::/0\s+.*$'
        line: 'host    all             all             ::/0                   md5'
        state: present
        backrefs: yes

    - name: Ensure PostgreSQL listens on all interfaces
      lineinfile:
        path: /etc/postgresql/14/main/postgresql.conf
        regexp: '^#?listen_addresses\s*='
        line: "listen_addresses = '*'"

    - name: Restart PostgreSQL to apply changes
      service:
        name: postgresql
        state: restarted
