- name: Deploy PostgreSQL Database
  hosts: db
  become: true
  vars:
    postgres_user: postgres
    postgres_password: postgres

  tasks:
    - name: Ensure APT cache is up to date
      apt:
        update_cache: yes
        cache_valid_time: 300
    - name: Install PostgreSQL
      apt:
        name: postgresql
        state: present
      become: true
      become_user: root
      when: ansible_os_family == "Debian"

    - name: Ensure PostgreSQL is started and enabled
      service:
        name: postgresql
        state: started
        enabled: yes

    - name: Set PostgreSQL password for the default user
      become_user: postgres
      shell: |
        psql -c "ALTER USER {{ postgres_user }} WITH PASSWORD '{{ postgres_password }}';"
      args:
        executable: /bin/bash